Game:
  roundTime: 10000 # En segundos
  bombTime: 10 # Tiempo hasta explosión
  bombDefuseDistance: 1
  buyTime: 10
  endTime: 5 #Tiempo de pantalla de final de ronda
  roundsPerSide: 1
  wonRoundMoney: 400
  lostRoundMoney: 250
  terrorSkin: 2
  counterSkin: 5

Player:
  health: 100
  speed: 6
  defuseTime: 2
  startingMoney: 1000

Weapons:
  Knife:
    damage: 15
    speed: 1 
  Pistol:
    maxDamage: 15
    minDamage: 25
    spread: 0.1
    falloff: 1
    speed: 0.2 #Tiempo entre disparos
    capacity: 10 #Balas por recarga
    reloadTime: 2
    maxRange: 100
  Rifle:
    maxDamage: 22
    minDamage: 18
    spread: 0.1
    falloff: 0.1
    burstTime: 0.1 #Tiempo entre disparos de la misma ráfaga
    speed: 0.4 #Tiempo entre ráfagas
    capacity: 30 #Balas por recarga
    reloadTime: 3
    maxRange: 100
    price: 1500
  Sniper:
    maxDamage: 90
    minDamage: 120
    spread: 0.05
    falloff: 0
    speed: 2.5 #Tiempo entre disparos
    capacity: 5 #Balas por recarga 
    reloadTime: 5
    maxRange: 100
    price: 2000
  Shotgun:
    bullets: 10
    maxDamage: 20
    minDamage: 15
    spread: 0.4
    falloff: 0.5
    speed: 2 #Tiempo entre disparos
    capacity: 5
    reloadTime: 3
    maxRange: 100
    price: 1200
  Bomb:
    speed: 1
